# Generated by Django 4.2 on 2023-06-08 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('Business Analytics', 'Business Analytics'), ('Deep Learning', 'Deep Learning'), ('Visualization', 'Visualization'), ('Data Science', 'Data Science'), ('Data Ethics', 'Data Ethics'), ('Math', 'Math'), ('NLP', 'NLP'), ('Statistics', 'Statistics'), ('SQL', 'SQL'), ('R studio', 'R studio'), ('Pyhton', 'Python')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(max_length=500)),
                ('authors', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytracker.category')),
            ],
        ),
    ]
